### ISSUE TITLE
Version published on rubygems is not the same as what's in this repo, breaks any Rails app it's included in

### ISSUE THREAD

**Issue by tfe** [stytchauth/stytch-ruby#43]
I couldn't get my app to boot after installing the gem, so I started browsing through the source via `bundle open stytch`. There's a lot of code there that appears to be leftover test/debug code that accidentally wound up in the published version of the gem.

For example: `client.rb` contains a reference to `https://test.nikhil.dev.stytch.com`; `stytch.rb` has this at the end:

```ruby
client = Stytch::Client.new(
    env: :test,
    project_id: "project-test-2a934f44-a014-425d-aa1d-76f2d0344db7",
    secret: "secret-test-z5kbR31dkcTnocolLJT77gkyX9KJQeU9umg="
)

resp = client.totps.authenticate(
    user_id: "user-test-fa9e1ba8-6786-4a7c-923f-a76a2b82e6a5",
    totp_code: "021363",
    session_token: "HLr0NGPZkyn7xA9Vc9XFjOIDjUafuTumOT6au3-PqM83",
)
puts resp
```

I never fully narrowed down what specifically was preventing a Rails app from booting, but when bundling the gem directly from GitHub it works fine. I did replicate the failure-to-boot on a fresh `rails new` app, for what it's worth.

Can you update the rubygems published version so that regular `gem install` and inclusion via bundler work as expected?

**Comment by nikhil-stytch** [comment]
Hi @tfe,

Thank you for identifying this issue! We've published a new gem that matches the code from Github.

Best,
Nikhil

**Comment by tfe** [comment]
👍 Looks good to me, thanks!
