### ISSUE TITLE
ETA for search endpoint?

### ISSUE THREAD

**Issue by rememberlenny** [stytchauth/stytch-ruby#48]
https://stytch.com/docs/api/search-users

**Comment by julianna-stytch** [comment]
hi Lenny - we're working on this now, should have an eta soon.

**Comment by jeremy-stytch** [comment]
It's done! Just released in [v3.1.0](https://github.com/stytchauth/stytch-ruby/releases/tag/v3.1.0)

If you run into problems or find something else missing, please start a new issue or reopen this one.
