### ISSUE TITLE
Upgrading Faraday

### ISSUE THREAD

**Issue by stephanie-teamshares** [stytchauth/stytch-ruby#72]
Stytch is dependent on an older version of Faraday, but multiple gems now require faraday > 2.0 for their newest versions. My app is currently unable to upgrade a couple different gems for this reason. So I'd like to submit a request to upgrade Faraday to 2.0.1 here so that users of stytch can upgrade their other gems.

**Comment by nicole-stytch** [comment]
Hey Stephanie, thanks for letting us know about this! I'll relay this to our team internally and see if we're able to bump the version.

**Comment by jordanfbrown** [comment]
We're also in the midst of upgrading Faraday to 2.0 and this will be a blocker for us. I see there's been a PR open since March: https://github.com/stytchauth/stytch-ruby/pull/74

Wondering what the status of the upgrade is at this point?

**Comment by mruhlin-stytch** [comment]
Hey all, closing this per https://github.com/stytchauth/stytch-ruby/pull/74, thanks again for flagging!
